### PR TITLE
feat: Actions for Mac and Ubuntu

### PR DESCRIPTION
**Pull request by im-coder-lg**
Test WIP
https://github.com/sumeshir26/TimerX/pull/8

### CODE REVIEW

**Comment by sumeshir26** [comment]
Looks good!

**Comment by im-coder-lg** [comment]
Not too good though

**Comment by im-coder-lg** [comment]
I realized the fail happened due to Ubuntu, it has first priority in the OS matrix.

**Comment by im-coder-lg** [comment]
It's the OS, not the steps.

**Comment by im-coder-lg** [comment]
Check this: https://github.com/im-coder-lg/TimerX/actions/runs/1540771062

**Comment by sumeshir26** [comment]
@im-coder-lg On Ubuntu the fail seems to happen due to the pywin32ibrary which dosent seem to be present on Ubuntu. Since acrilic is buggy, it  will not be included in the 1.0 release so i will just comment out those lines and the build wont probably fail anymore

**Comment by sumeshir26** [comment]
@im-coder-lg https://github.com/pyinstaller/pyinstaller/wiki/FAQ#mac-os-x

**Comment by sumeshir26** [comment]
Also,try this https://py2app.readthedocs.io/en/latest/index.html

**Comment by im-coder-lg** [comment]
Well, that's macOS. We still need to understand Linux builds.
The folks at PyInstaller reached out to me, and I think they are helping here, they said they use the shell scripts. But what confuses me is this: can I edit the `setup.py` file and make sure it supports TimerX? I have asked this there, still no response. Will keep you updated.

**Comment by sumeshir26** [comment]
@im-coder-lg Which setup.py file? The TimerX one or the PyChess one?
If you are feeling frustrated with this Pr, just give me write access to the acgtions-fix branch an i will figure this out myself. Thank you for all the help, BTW.

**Comment by im-coder-lg** [comment]
> Which setup.py file? The TimerX one or the PyChess one?

The PyChess one.

> If you are feeling frustrated with this Pr, just give me write access to the acgtions-fix branch an i will figure this out myself. Thank you for all the help, BTW.

I am not frustrated, and also if you can help, since I added you as a collaborator, you can edit from the repo itself.
My PyChess issue was closed, I will report back.

**Comment by im-coder-lg** [comment]
Thanks for the help, man. I am currently a bit tired, but I will push commits after I get rid of that tiredness.

**Comment by sumeshir26** [comment]
Hey @im-coder-lg Made the setup file for MacOS! Since I am trash at Github Actions, can you modify `release.yml` to also add `dist/TimerX.app` to the release after running `pip install packager-requirements.txt && python setup.py py2app`

**Comment by im-coder-lg** [comment]
Will do it soon!

**Comment by sumeshir26** [comment]
@im-coder-lg Can I merge it for MacOS for now? Linux can be added in separate PR?

**Comment by im-coder-lg** [comment]
Hmm... Okay.

**Comment by im-coder-lg** [comment]
Just remove Linux components and then go ahead.

**Comment by sumeshir26** [comment]
@im-coder-lg Also, can you tell me the issues you found in the app that should be fixed before 1.0?

**Comment by im-coder-lg** [comment]
1. Double-clicking Play to start
2. Acrylic(optional feature, commented out) is bright in bright areas and dark in dark areas
3. Icon problems when running new build

That's all I have noticed.

**Comment by sumeshir26** [comment]
@im-coder-lg 
> Icon problems when running new build
Try now

**Pull request merged**
